/**
 *  @author  Yunxiang He
 *  @date    Jan 4, 2018 11:02:29 PM
 */

package leetcode;

/*

Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.

 */

public class _0389_Find_the_Difference {

    /**
     * Solution:
     * XOR
     * --------------------------------------------------------------
     * Tips:
     * XOR all elements, then it will find the different one
     * --------------------------------------------------------------
     *  Time complexity : O(n)
     * Space complexity : O(1)
     */
    public char findTheDifference(String s, String t) {
        char sum_s = 0;
        char sum_t = 0;
        for (char _s : s.toCharArray()) {
            sum_s ^= _s;
        }
        for (char _t : t.toCharArray()) {
            sum_t ^= _t;
        }
        return (char) (sum_t ^ sum_s);
    }

    public static void main(String[] args) {
        _0389_Find_the_Difference test = new _0389_Find_the_Difference();
        System.out.println(test.findTheDifference("abcd", "ebacd"));
    }
}
